import os

def main():
    output_dir = "build"
    os.makedirs(output_dir, exist_ok=True)

    html = """
    <!DOCTYPE html>
    <html>
    <head>
        <title>Hello from app.py</title>
    </head>
    <body>
        <h1>Hello, World! 🚀</h1>
        <p>This page was generated by <code>app.py</code>.</p>
    </body>
    </html>
    """

    with open(os.path.join(output_dir, "index.html"), "w", encoding="utf-8") as f:
        f.write(html)

if __name__ == "__main__":
    main()
